name: "Code Lint Check"
on: [push, pull_request]
env:
  NODE_VERSION: 18
jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: 8
      - name: Run Biome
        run: biome ci .
